import moment from 'moment';
import { ConnectionConfig, DbConfig, TableListObject } from './types';

export const dbConfig: DbConfig = {
  client: 'mssql',
  version: '7.2',
  useNullAsDefault: true,
  connection: undefined,
};

export const connectionConfig: ConnectionConfig = {
  host: process.env.DB_HOST ? process.env.DB_HOST : 'localhost',
  user: 'sa',
  password: process.env.DB_PASSWORD
    ? process.env.DB_PASSWORD
    : 'StrongPassword123%',
  database: '',
  timezone: '+00:00',
  dateStrings: true,
  typeCast: (field, next) => {
    if (field.data_type === 'date') {
      return moment(field.string()).format('Y-MM-DD');
    }
    if (field.data_type === 'datetime') {
      return moment(field.string()).format('Y-MM-DD HH:mm:ss');
    }
    return next();
  },
};

export const dbList: Array<string> = ['DbDent', 'DbStorico', 'DbEsercizio'];

export const tableList: Array<TableListObject> = [
  {
    tableName: 'Agenda',
    hasStorico: true,
    targetDb: 'DbDent',
    targetStorico: 'DbStorico',
  },
  {
    tableName: 'Pazienti',
    hasStorico: true,
    targetDb: 'DbDent',
    targetStorico: 'DbStorico',
  },
  {
    tableName: 'Dentisti',
    hasStorico: true,
    targetDb: 'DbDent',
    targetStorico: 'DbStorico',
  },
  {
    tableName: 'Fornitori',
    hasStorico: true,
    targetDb: 'DbDent',
    targetStorico: 'DbStorico',
  },
  {
    tableName: 'Magazzino',
    hasStorico: true,
    targetDb: 'DbDent',
    targetStorico: 'DbStorico',
  },
  {
    tableName: 'Lavori',
    hasStorico: true,
    targetDb: 'DbDent',
    targetStorico: 'DbStorico',
  },
  {
    tableName: 'LavoriDettagli',
    hasStorico: true,
    targetDb: 'DbDent',
    targetStorico: 'DbStorico',
  },
  { tableName: 'Preventivi', hasStorico: false, targetDb: 'DbEsercizio' },
  {
    tableName: 'PreventiviDettagli',
    hasStorico: false,
    targetDb: 'DbEsercizio',
  },
  { tableName: 'Fatture', hasStorico: false, targetDb: 'DbEsercizio' },
  { tableName: 'FattureDettagli', hasStorico: false, targetDb: 'DbEsercizio' },
  {
    tableName: 'Richiami',
    hasStorico: true,
    targetDb: 'DbDent',
    targetStorico: 'DbStorico',
  },
];

export const tableStructureQuery = (tableName: string): string => `
  SELECT
    c.object_id 'Id',
    c.name 'col_name',
    t.Name 'data_type',
    c.max_length 'max_length',
    c.precision ,
    c.scale ,
    c.is_nullable,
    (CASE WHEN pk.column_id IS NULL THEN 0 ELSE 1 END) 'p_key'
  FROM
    sys.columns c
  INNER JOIN
    sys.types t ON c.user_type_id = t.user_type_id
  LEFT OUTER JOIN
    (
        SELECT ic.object_id, ic.column_id
        FROM sys.index_columns ic
        INNER JOIN sys.indexes i ON ic.object_id = i.object_id AND ic.index_id = i.index_id
        WHERE i.is_primary_key = 1
    ) pk ON c.object_id = pk.object_id AND c.column_id = pk.column_id
  WHERE
    c.object_id = OBJECT_ID('orisdentevo.${tableName}')
`;

export const agendaQuery = (isStorico: boolean = false): string =>
  `
  SELECT
    ID_AGENDA,
    ID_PAZIENTE,
    ID_LAVORO,
    ID_DENTISTA,
    [DATA],
    DALLE,
    ALLE,
    CONVERT(VARCHAR(255),DECRYPTBYPASSPHRASE('${
      process.env.DECRYPT_PASSPHRASE
    }',DESCRIZIONE)) as DESCRIZIONE,
    NOTE,
    BACKCOLOR,
    FORECOLOR,
    PICTURE,
    TIPO,
    STATOAPPUNTAMENTO,
    ORARIOARRIVO,
    AGELIMINATO,
    AGDATA,
    ID_POLTRONA,
    ORARIOFINE,
    CODICESYNC,
    ORARIOCURA,
    ORARIORITARDO,
    ORARIOATTESA,
    ORARIOLAVORO,
    PRENOTAZIONE,
    ID_DETTAGLIO2,
    ID_RICHIAMO,
    DESC_TIPOAPP,
    DESC_MEDIA,
    DESC_CAMPAGNA,
    ID_TUTORE,
    ID_OPERATOREAPP,
    DATAREGAPP,
    PRIMAVISITA,
    SALAATTESA,
    DURATAMIN,
    RITARDOAPPUNTAMENTO,
    ID_APPUNTAMENTO,
    NSEDUTA,
    RICORDAAPP,
    ID_APP_EXT,
    ID_PREVENTIVO,
    NSEDUTAPREVENTIVO,
    NOTEAGGIUNTIVE,
    ESCLUDIAPP,
    PRS_NOTAIMPORTANTE,
    DATADINASCITA,
    LUOGODINASCITA,
    PROVINCIADINASCITA,
    INDIRIZZO,
    CITTA,
    PROVINCIA,
    ASL_CODICEREGIONE,
    ASL_CODICEDISTRETTO,
    ID_SPECIALIZZAZIONEATTESA,
    ID_AGENDACOLLEGATO,
    IDSEDE,
    IDCONFIGURAZIONE,
    DATASYNC,
    CODICESYNCPADRE,
    STATODELETESYNC,
    PRS_CODICEESTERNO,
    AG_TELEFONOABITAZIONE,
    AG_TELEFONOUFFICIO,
    AG_FAX,
    AG_E_MAIL,
    null as Id_AppuntamentoTriage,
    null as Triage,
    null as COVID19_DataInvioSmsStatoPronto,
    null as ID_OperatoreUltimaMod,
    null as DataUltimaMod
  FROM
    ${isStorico ? 'DbStorico' : 'DbDent'}.orisdentevo.Agenda;
`;

export const pazientiQuery = (isStorico: boolean = false): string => `
  SELECT
    ID_PAZIENTE,
    ID_DENTISTA,
    PROFESSIONE,
    CONVERT(VARCHAR(255),DECRYPTBYPASSPHRASE('${
      process.env.DECRYPT_PASSPHRASE
    }',RAGIONESOCIALE)) as RAGIONESOCIALE,
    CONVERT(VARCHAR(255),DECRYPTBYPASSPHRASE('${
      process.env.DECRYPT_PASSPHRASE
    }',COGNOME)) as COGNOME,
    CONVERT(VARCHAR(255),DECRYPTBYPASSPHRASE('${
      process.env.DECRYPT_PASSPHRASE
    }',NOME)) as NOME,
    VIA,
    CAP,
    CITTA,
    DATADINASCITA,
    LUOGODINASCITA,
    TELEFONOABITAZIONE,
    TELEFONOUFFICIO,
    FAX,
    CONVERT(VARCHAR(255),DECRYPTBYPASSPHRASE('${
      process.env.DECRYPT_PASSPHRASE
    }',CODICEFISCALE)) as CODICEFISCALE,
    FOTO,
    TIPO,
    SESSO,
    DATAULTIMAVISITA,
    DATAPROSSIMAVISITA,
    DATAPRIMAVISITA,
    DATAULTIMOINCASSO,
    NOTE,
    SCONTO,
    ASSICURAZIONE,
    MEDICOCURANTE,
    TELEFONOMEDICOCURANTE,
    USL,
    SSN,
    ADULTOBAMBINO,
    D1MD,
    D1MA,
    D2MD,
    D2MA,
    D3MD,
    D3MA,
    D4MD,
    D4MA,
    D5MD,
    D5MA,
    D6MD,
    D6MA,
    D1PD,
    D1PA,
    D2PD,
    D2PA,
    D3PD,
    D3PA,
    D4PD,
    D4PA,
    D5PD,
    D5PA,
    D6PD,
    D6PA,
    CONVERT(VARCHAR(255),DECRYPTBYPASSPHRASE('${
      process.env.DECRYPT_PASSPHRASE
    }',IFRAGIONESOCIALE)) as IFRAGIONESOCIALE ,
    IFVIA,
    IFCITTA,
    IFCAP,
    CONVERT(VARCHAR(255),DECRYPTBYPASSPHRASE('${
      process.env.DECRYPT_PASSPHRASE
    }',IFCODICEFISCALE)) as IFCODICEFISCALE,
    IFPIVA,
    NOMELISTINO,
    LISTINO,
    CONVENZIONE,
    PAZIENTE,
    PIVA,
    MODPAGAMENTO,
    ETA,
    BARCODE,
    CONSENSO,
    RRISERVATEZZA,
    DATADINASCITAFAT,
    LUOGODINASCITAFAT,
    PROVINCIADINASCITAFAT,
    PROVINCIA,
    PROVINCIADINASCITA,
    IFPROVINCIA,
    CODICEGENDEX,
    DATACREAZIONE,
    CODICEVILLA,
    ID_FAMIGLIA,
    TIPOPARENTELA,
    CODICEAFFILIATO,
    CODICEMATRICOLA,
    DATAFINE,
    CODICESOCIETA,
    CODICENOVAXA,
    NAZIONE,
    NAZIONENASCITA,
    NAZIONENASCITAFAT,
    NAZIONEFAT,
    CODICEJULIE,
    NUMEROCONTRIBUENTE,
    SITO,
    TIPOCONVENZIONE,
    SESSOFAT,
    DATASCADCONV,
    TIPOLOGIAPAZIENTE,
    STATOCIVILE,
    TITNOTA1,
    TITNOTA2,
    TITNOTA3,
    TITNOTA4,
    TITNOTA5,
    TITNOTA6,
    TITNOTA7,
    TITNOTA8,
    NOTA1,
    NOTA2,
    NOTA3,
    NOTA4,
    NOTA5,
    NOTA6,
    NOTA7,
    NOTA8,
    D7MA,
    D7MD,
    D7PD,
    D7PA,
    LINGUA,
    VALUTAPUNTO,
    VALOREPUNTO,
    TITOLO,
    IFTITOLO,
    CODICEESPORTAFATTURA,
    NUMERORIFERIMENTO,
    FORZAREGIONE,
    E_MAIL,
    CODICEIMAGEX,
    SMSNOCONS,
    IMPRONTASUP,
    IMPRONTAINF,
    CODICEDEXIS,
    CODICEDENTALFOCUS,
    CONV_STAMPACODICE,
    CONV_STAMPADATADINASCITA,
    CODICEORISCEPH,
    CODICEANTHOS,
    CODICEVISIODENT,
    AGELIMINATO,
    AGDATA,
    ASL_CODICEFISCALEMEDICO,
    ASL_CODICEPRESCRITTORE,
    ASL_TIPOLOGIAMEDICO,
    ASL_CODICETIPOLOGIAMEDICO,
    ASL_TIPOLOGIAESENZIONE,
    ASL_CODICEESENZIONE,
    ASL_TIPOLOGIARICETTA,
    ASL_CODICETIPOLOGIARICETTA,
    ASL_USAFRANCHIGIA,
    ASL_USARICETTA,
    ASL_VALUTAFRANCHIGIA,
    ASL_IMPORTOFRANCHIGIA,
    ASL_USADIRETTA,
    ASL_USARIMBORSOPAZIENTE,
    NOEMAIL,
    ASL_MAXVOCIRICETTA,
    PRS_CODICEESTERNO,
    ASL_MODFASI,
    ASL_CODICEASL,
    ASL_CODICEREGIONE,
    ASL_PROVINCIAMEDICO,
    ASL_TIPOLOGIAMEDICO2,
    ASL_CODICEDISTRETTO,
    RIFASSICURAZIONE,
    FLAGNOTAIMPORTANTE,
    ULTIMOUTILIZZO,
    ASL_TICKETADDIZIONALE,
    ID_PAZIENTEEDUCO,
    DESCRIZIONECANALE,
    DATACANALE,
    ORACANALE,
    DESC_MEDIA,
    ID_OPERATORECREAZIONE,
    ID_OPERATORECONSENSO,
    DATACONSENSO,
    ID_OPERATORETRATTAMENTO,
    DATATRATTAMENTO,
    ID_OPERATOREANAMNESI,
    DATAANAMNESI,
    ANAMNESI,
    STATOPAZIENTE,
    PRSA33_CONSENTITELEFONATE,
    PRSA34_GESTIONEDOCCONV,
    CODICECEFLA,
    PRSA34_PATHINPUT,
    PRSA34_PATHOUTPUT,
    CARTAIDENTITANUMERO,
    CARTAIDENTITASCADENZA,
    FINERAPPPAZ,
    DESCFINERAPPPAZ,
    DATAFINERAPPPAZ,
    CAPOFAMIGLIA,
    PRSA34_MAILDOC,
    PRSA40_CODICECONVENZIONEEXPORT,
    CONV_RITENUTA,
    PRSA38_CONSENSOGRAFOMETRICA,
    PROPENSIONEESTETICA,
    MAILNOCONS,
    ID_APP,
    PWD_APP,
    NOTIFICANOCONS,
    ID_PAZ_EXT,
    CODICERADIS,
    CODICECDXVIEW,
    CONSENSO_COMM,
    DATACONSENSO_COMM,
    CODICEPA,
    CHECKSALDOPOSITIVO,
    MYSMILE_SYNC,
    BM_STATUS,
    TIPOPAZIENTESSN,
    ASL_E10,
    QID,
    SCADENZAQID,
    AZIONEMASTER,
    DATAAZIONEMASTER,
    CODICEPAESE,
    ZONA,
    CODNUMPAESE,
    DECEDUTO,
    SCHEDAPAZ,
    DISATTIVAPROFILAZIONE,
    EMAIL_FAT,
    BUILDINGNUMBER,
    CONVSECONDARIA,
    NOMELISTINO2,
    CONVENZIONE2,
    DATASCADCONV2,
    SCONTOCLAIMS,
    MODELLOCLAIMS,
    LIMITECONV1,
    LIMITECONV2,
    CODICELUOGO,
    CODICEPRESCRITTOREPT,
    CODICECOUPON,
    CLAIMPAYERID,
    CODICECOUPONVALIDO,
    GDPR_OBLIO,
    GDPR_PRIVACY,
    GDPR_AUTORIZZAMARKETING,
    IDSEDE,
    IDCONFIGURAZIONE,
    CODICESYNC,
    DATASYNC,
    CODICESYNCPADRE,
    STATODELETESYNC,
    E_MAILPEC,
    IFE_MAILPEC
  FROM
    ${isStorico ? 'DbStorico' : 'DbDent'}.orisdentevo.PAZIENTI
`;

export const dentistiQuery = (isStorico: boolean = false): string => `
  SELECT *
  FROM ${isStorico ? 'DbStorico' : 'DbDent'}.orisdentevo.Dentisti d
`;

export const fornitoriQuery = (isStorico: boolean = false): string => `
  SELECT *
  FROM ${isStorico ? 'DbStorico' : 'DbDent'}.orisdentevo.Fornitori f
`;

export const magazzinoQuery = (isStorico: boolean = false): string => `
  SELECT *
  FROM ${isStorico ? 'DbStorico' : 'DbDent'}.orisdentevo.Magazzino m
`;

export const lavoriQuery = (isStorico: boolean = false): string => `
  SELECT *
  FROM ${isStorico ? 'DbStorico' : 'DbDent'}.orisdentevo.Lavori l
`;

export const LAVORI_DETTAGLI_QUERY: string = `
  SELECT *
  FROM DbDent.orisdentevo.LavoriDettagli ld
`;

export const preventiviQuery = (): string => `
  SELECT
    ID_PREVENTIVO,
    ID_DENTISTA,
    ID_PAZIENTE,
    RIF_PREV,
    DESCRIZIONE,
    [DATA],
    SCADENZA,
    BOLLO,
    IMPORTO,
    TOTALE,
    MODPAGAMENTO,
    DATASCADENZA,
    STP1,
    STP2,
    STP3,
    STP4,
    STP5,
    STAMPA,
    IVA,
    CONVERT(VARCHAR(255),DECRYPTBYPASSPHRASE('${process.env.DECRYPT_PASSPHRASE}',RAGIONESOCIALE)) as RAGIONESOCIALE,
    VIA,
    CAP,
    CITTA,
    PROVINCIA,
    PIVA,
      CONVERT(VARCHAR(255),DECRYPTBYPASSPHRASE('${process.env.DECRYPT_PASSPHRASE}',CODICEFISCALE)) as CODICEFISCALE,
    VALUTA,
    SCONTOFISSO,
    NOTE,
    MEMONOTE1,
    MEMONOTE2,
    MEMONOTE3,
    MEMONOTE4,
    MEMONOTE5,
    MEMONOTE6,
    ND1,
    ND2,
    NC1,
    NC2,
    VALOREPUNTO,
    TITOLO,
    TOTALECONVENZIONE,
    SCONTO,
    PRS_MATRICOLA,
    PRS_TIPOPARENTELA,
    PRS_TIPOSALDO,
    PRS_CODICEPAZIENTE,
    PRS_CODICEAFFILIATO,
    PRS_RAGIONESOCIALE,
    PREVRIFIUTATO,
    DATARIFIUTO,
    MOTIVAZIONERIFIUTO,
    ID_TUTORE,
    ID_OPERATORECREAZIONE,
    ID_OPERATOREACCETTAZIONE,
    DATACREAZIONE,
    ID_OPERATORECONSENSO,
    DATACONSENSO,
    DESC_MEDIA,
    DESC_CAMPAGNA,
    PRESAVISIONE,
    PREVPRIMAVISITA,
    PRSA34_NOMECONVENZIONE,
    ID_OPERATOREULTIMAMOD,
    DATAULTIMAMOD,
    TELEFONO,
    PRSA34_MODPREV,
    ID_ASSISTENTE,
    PRSA44_STATOPREVENTIVO,
    IMPORTOACCETTATO,
    IMPORTOACCETTATOCONV,
    DIAGNOSI1,
    DIAGNOSI2,
    RIMANENZA_PRSA72,
    PRSA79_DOCENTRY,
    PRSA87_TIPOLOGIA,
    PRSA87_DATAPRESENTAZIONE,
    PRSA87_PREVORIGINE,
    ID_DENTISTA_AUTORIZZAZIONESCONTO,
    PRSA87_PARZIALE,
    PREAUTORIZZAZIONE,
    INTRAORALE,
    EXTRAORALE,
    ECLAIM_STATOPREV,
    PRS_INVIATOCUP,
    PRSA87_STATOPREVENTIVO,
    IDSEDE,
    IDCONFIGURAZIONE,
    CODICESYNC,
    DATASYNC,
    CODICESYNCPADRE,
    AGDATA,
    AGELIMINATO,
    STATODELETESYNC,
    PRSA87_CODICETESSERA,
    PRSA87_SCONTOAPPLICATO,
    null as PRSA21_NUMERO_RATE,
    null as PRSA21_IMPORTO_RATA,
    null as PRSA21_NOTE,
    null as PRSA21_DESCRIZIONERATA,
    null as HASHPREVENTIVO,
    null as NUMERAZIONE_SAFT,
    null as SAFTPT_Versione,
    null as ID_ImpostazioniStampa,
    null as IvaDefault,
    null as ID_CodiceIva,
    null as ID_CodiceIvaNoImp,
    null as IVAMULTI,
    null as IVAVALORE,
    null as IVAVALORECONV,
    null as ProForma,
    null as ID_DentistaFiscale,
    null as Rif_Prev2Text,
    null as Copy,
    null as STAMPATO,
    null as HashControl,
    null as ID_Specializzazione
  FROM
    DbEsercizio.orisdentevo.PREVENTIVI
`;

export const PREVENTIVI_DETTAGLI_QUERY: string = `
  SELECT *
  FROM DbEsercizio.orisdentevo.PreventiviDettagli pd
`;

export const fattureQuery = (): string => `
  SELECT
    ID_FATTURA,
    ID_DENTISTA,
    ID_PAZIENTE,
    ID_LAVORO,
    RIF_FATT,
    DESCRIZIONE,
    [DATA],
    SCADENZA,
    IMPORTO,
    TOTALE,
    MODPAGAMENTO,
    DATASCADENZA,
    MEMO5,
    STP1,
    STP2,
    STP3,
    STP4,
    STP5,
    STAMPA,
    BOLLO,
    IVA,
    CONTEGGIABOLLO,
    TIPOFATTURA,
    PAGATA,
    CONVERT(VARCHAR(255),DECRYPTBYPASSPHRASE('${process.env.DECRYPT_PASSPHRASE}',RAGIONESOCIALE)) as RAGIONESOCIALE,
    VIA,
    CAP,
    CITTA,
    PROVINCIA,
    PIVA,
    CONVERT(VARCHAR(255),DECRYPTBYPASSPHRASE('${process.env.DECRYPT_PASSPHRASE}',CODICEFISCALE)) as CODICEFISCALE,
    PAZIENTE,
    VALUTA,
    SCONTOFISSO,
    RITENUTA,
    RIF_FATT2TEXT,
    CONVENZIONE,
    NUMEROPAGAMENTO,
    TOTALECONVENZIONE,
    ND1,
    ND2,
    NC1,
    NC2,
    VALOREPUNTO,
    ID_PAZIENTECONVENZIONATO,
    LUOGO,
    SPESESPEDIZIONE,
    TITOLO,
    TOTALELABORATORIO,
    TOTALEPAGATO,
    TOTALEPAGAMENTOANTICIPATO,
    ID_GRUPPO,
    NUMDOC,
    NUMERORICHIAMO,
    RIGACOD,
    BANCAUBS,
    CLIENTEUBS,
    TIPODOCUMENTO,
    ANNULLATA,
    VALOREMINIMOBOLLO,
    BOLLODEFAULT,
    VALUTABOLLO,
    IVADEFAULT,
    ID_CONVENZIONERIMBORSO,
    CONVERT(VARCHAR(255),DECRYPTBYPASSPHRASE('${process.env.DECRYPT_PASSPHRASE}',RAGIONESOCIALE2)) as RAGIONESOCIALE2,
    NUOVAMODALITA,
    ID_CODICEIVA,
    ID_CODICEIVAESENTE,
    ID_CODICEIVANOIMP,
    ID_DENTISTACOMPENSO,
    VOCEQUADRATURANA,
    NUMREG,
    DATAREG,
    TICKET,
    MEMO1,
    MEMO2,
    MEMO3,
    MEMO4,
    SCONTO,
    COMPENSOEROGATO,
    DATAEROGAZIONE,
    MODCONVDIRETTA,
    PRS_TIPOSALDO,
    PRS_MATRICOLA,
    PRS_IDPREVENTIVO,
    PRS_TIPOPARENTELA,
    PRS_RAGIONESOCIALE,
    RIFASSICURAZIONE,
    HASHFATTURA,
    MOTIVOANNULLAMENTO,
    DATAMODIFICA,
    NUMERAZIONE_SAFT,
    OPERATORECREAZIONEFATT,
    DATACREAZIONEFATT,
    OPERATOREULTIMAMODFATT,
    DATAULTIMAMODFATT,
    PRS_ANAGRAFICAPAZIENTE,
    PRS_QUIETANZADACONVENZIONE,
    PRSA34_QUOTAPAZ,
    PRSA34_QUOTACONV,
    PRSA34_NOMECONVENZIONE,
    PRSA34_MODCONVDOC,
    BOLLOVIRTUALE,
    CONV_RITENUTA,
    ID_SPECIALIZZAZIONE,
    NAZIONALITA,
    TIPOFATTURAACCONTO,
    ESCLUDIDASPESOMETRO,
    PRS_PROVENIENZAPAZIENTE,
    PRS_TIPOLOGIAPAZIENTE,
    PRS_PTC,
    MODOFATTURAZIONE,
    WK21U_TIPOLOGIAATTIVITA,
    WK21U_ALTRIELEMENTI,
    IVAMULTI,
    IVAVALORE,
    IVAVALORECONV,
    RIF_FATT3TEXT,
    CHECK_FATTURAELETTRONICA,
    CHECK_ESPORTAZIONE,
    FATTURAPAEXPORT,
    FATTURAPAPATH,
    FATTURAPASCADCERT,
    FATTURAPATRASMITTENTE,
    FATTURAPATRASMITTENTEID,
    FATTURAPACEDENTE,
    FATTURAPACEDENTEID,
    FATTURAPALEGALDOCINDEX,
    INVIA,
    PRSA44_NUM_FATTURA_EXT,
    PRSA63_TIPOFATTURA,
    PRSA44_INVIATA,
    IMPORTOSPESASR,
    IMPORTOSPESAIC,
    IMPORTOSPESAAA,
    SPESASANITARIAMANUALE,
    IMPORTOSPESATK,
    SPESASANITARIANOINVIO,
    STATOEXP730,
    DATAEXP730,
    INVIATAEXP730,
    PROTOCOLLOEXP730,
    ESITOEXP730,
    NOTAOPPOSIZIONE730,
    STAMPANOTAOPPOSIZIONE730,
    NAZIONE,
    IDMARCABOLLO,
    IMPORTOSPESAPI,
    FATTURAPATOKEN,
    FATTURAPATOKENLOTTO,
    FATTURAPATOKENRETT,
    ID_PAZIENTEINTESTAZIONE,
    PRS_IDFATTESTERNO,
    PRS_IDTESSERAPAZIENTE,
    STATOEMISSIONEFATTURA,
    NUMEROAPPROVAZIONE,
    TOTALECONVENZIONE2,
    PRSA69_SECONDDOCUMENTDATE,
    PRSA69_INVIATA,
    SCONTOTESSERA,
    ACCUMULOTESSERA,
    IDSEDE,
    IDCONFIGURAZIONE,
    CODICESYNC,
    DATASYNC,
    CODICESYNCPADRE,
    AGDATA,
    AGELIMINATO,
    STATODELETESYNC,
    ACCUMULOTESSERAPADRE,
    MODPAGAMENTOE,
    B2B_PEC,
    B2B_CODICEDESTINATARIO,
    B2B_STATOFATTURA,
    B2B_STATOTRASMISSIONE,
    B2B_NOTA,
    B2B_XMLFATTURA,
    B2B_XMLRICEVUTA,
    B2B_DATAULTIMAMODIFICA,
    B2B_CODICETRASMISSIONE,
    B2B_MODALITA,
    B2B_CONSEGNATA,
    RIFFATTSTORNATA,
    B2B_RIFERIMENTON4,
    B2B_RIFERIMENTON1,
    B2B_IBAN,
    B2B_CODICEUFFICIOPOSTALE,
    B2B_OPZIONIPAGAMENTO,
    B2B_CONSERVATA,
    B2B_TOKEN,
    B2B_TOKENRETTIFICATO,
    null as B2B_RIFERIMENTON6,
    null as INVERSIONECONTABILE,
    null as B2B_RIFERIMENTON2,
    null as B2B_RIFERIMENTON3,
    null as B2B_RIFERIMENTON7,
    null as B2B_RIFERIMENTON1IVA,
    null as PRSA21_TipologiaFattura,
    null as PRSA21_FatturaConIva,
    null as MetodoPagamento,
    null as A28_PCPT,
    null as StampaNoModifica,
    null as B2B_Versione,
    null as NATURA,
    null as ATCUD,
    null as QR,
    null as ImportoSpesaSP,
    null as SAFTPT_Versione,
    null as DocumentNumberPrint,
    null as ID_ImpostazioniStampa,
    null as codicesocieta,
    null as motivo,
    null as HashControl,
    null as B2B_TipoDocumento,
    null as B2B_RegimeFiscale,
    null as SpesaSanitariaSentId,
    null as StatoInvioWSExp730,
    null as DataUltimoInvioWSExp730,
    null as ErrorTextWSExp730
  FROM
    DbEsercizio.orisdentevo.FATTURE;
`;

export const FATTURE_DETTAGLI_QUERY: string = `
  SELECT *
  FROM DbEsercizio.orisdentevo.FattureDettagli fd
`;

export const richiamiQuery = (isStorico: boolean = false): string => `
  SELECT *
  FROM ${isStorico ? 'DbStorico' : 'DbDent'}.orisdentevo.Richiami r
`;
